version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34.1
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-159-138-67.compute-1.amazonaws.com
            port: '5432'
            database: d5b5bsskhr019o
            ssl: true
            user: yhacwvyzjjxegq
            password: 86134ff4dc870de294f225f58ac70f5229bf3ec149bc953116c1903fbdf5ea5d
            migrations: true